export const genres = [
    "Art & Design",
    "Pretend Play",
    "Creativity",
    "Action & Adventure",
    "Auto & Vehicles",
    "Beauty",
    "Books & Reference",
    "Business",
    "Comics",
    "Communication",
    "Dating",
    "Education;Education",
    "Education",
    "Music & Video",
    "Brain Games",
    "Entertainment",
    "Events",
    "Finance",
    "Food & Drink",
    "Health & Fitness",
    "House & Home",
    "Libraries & Demo",
    "Lifestyle",
    "Arcade",
    "Casual",
    "Card",
    "Action",
    "Strategy",
    "Puzzle",
    "Sports",
    "Music",
    "Word",
    "Racing",
    "Simulation",
    "Adventure",
    "Board",
    "Trivia",
    "Role Playing",
    "Educational",
    "Music & Audio",
    "Video Players & Editors",
    "Medical",
    "Social",
    "Shopping",
    "Photography",
    "Travel & Local",
    "Tools",
    "Personalization",
    "Productivity",
    "Parenting",
    "Weather",
    "News & Magazines",
    "Maps & Navigation",
    "Casino"
]

export const categories = [
    "ART_AND_DESIGN",
    "AUTO_AND_VEHICLES",
    "BEAUTY",
    "BOOKS_AND_REFERENCE",
    "BUSINESS",
    "COMICS",
    "COMMUNICATION",
    "DATING",
    "EDUCATION",
    "ENTERTAINMENT",
    "EVENTS",
    "FINANCE",
    "FOOD_AND_DRINK",
    "HEALTH_AND_FITNESS",
    "HOUSE_AND_HOME",
    "LIBRARIES_AND_DEMO",
    "LIFESTYLE",
    "GAME",
    "FAMILY",
    "MEDICAL",
    "SOCIAL",
    "SHOPPING",
    "PHOTOGRAPHY",
    "SPORTS",
    "TRAVEL_AND_LOCAL",
    "TOOLS",
    "PERSONALIZATION",
    "PRODUCTIVITY",
    "PARENTING",
    "WEATHER",
    "VIDEO_PLAYERS",
    "NEWS_AND_MAGAZINES",
    "MAPS_AND_NAVIGATION"

]

export const contentRatings = [
    "Everyone",
    "Teen",
    "Everyone 10+",
    "Mature 17+",
    "Adults only 18+",
    "Unrated"
]
